display_name: Pure Live
publisher_display_name: liuchuancong
identity_name: com.mystyle.purelive
logo_path: assets/icons/icon.png
capabilities: internetClient
languages: zh-cn
install_certificate: "false"