name: pure_live
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.7.4

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  #hashlib
  hashlib: ^1.21.1
  # network
  flutter_js: 0.8.2
  html: ^0.15.5
  http: ^1.1.0
  url_launcher: ^6.3.1
  web_socket_channel: ^3.0.1
# cached_network_image: ^3.3.0
  
  # ui related
  dynamic_color: ^1.6.8
  flutter_staggered_grid_view: ^0.7.0
  #Widget
  easy_refresh: ^3.4.0
  flutter_smart_dialog: ^4.9.8+5 #各种弹窗 Toast/Dialog/Popup
  # barrage wall
  quiver: ^3.2.1
  flex_color_picker: ^3.7.0
  flutter_exit_app: ^1.1.2
  visibility_detector: ^0.4.0+2
  # database
  supabase_flutter: ^2.8.3
  email_validator: ^3.0.0
  font_awesome_flutter: ^10.8.0
  # video player mobile
#  media_kit: ^1.1.11                          # Primary package.
#  media_kit_video: ^1.2.5                        # For video rendering.
#  media_kit_libs_video: ^1.0.5                   # Native video dependencies.
  gsy_video_player: ^0.0.6
#    git: https://github.com/liuchuancong/gsy_video_player.git
  fvp: ^0.31.2                              # FVP 视频播放器
  video_player: 2.9.2                      #  视频播放器
  chewie: ^1.9.0                      #  视频播放器
  share_handler: ^0.0.22
  uri_to_file: ^1.0.0
  bordered_text: ^2.0.0
#  screen_brightness: ^0.2.2+1 # 屏幕亮度
#  screen_brightness_linux: ^0.1.0-dev.1 # 屏幕亮度
  screen_brightness: ^2.1.1 # 屏幕亮度
  flutter_volume_controller: ^1.3.3  # 声音
  flutter_color: ^2.1.0
  crypto_simple: ^3.0.0
  window_manager: ^0.4.3
#  url_protocol:
#    git:
#      url: https://github.com/LucasXu0/flutter_url_protocol
#      commit: 77a8420
  win32_registry: ^1.1.5
  windows_single_instance: ^1.0.0
  app_links: ^6.3.3
  protobuf: ^3.1.0
  fixnum: ^1.1.1 # 32位，64位 数字
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.1
  dio_cache_interceptor: ^3.5.1
  dio_cache_interceptor_db_store: ^6.0.0
  dio_compatibility_layer: ^0.1.0 # 允许 dio 使用 http 包
#  rhttp: ^0.9.8  # 使用 rust 请求http
#    git:
#      url: https://ghfast.top/https://github.com/Tienisto/rhttp.git
#      commit: 8ed4752 # 0.9.2 support text body compressed in gzip and brotli
#      path: rhttp
  flutter_cache_manager_dio: ^4.0.0
  cookie_jar: ^4.0.8
  # system hardware utils
  wakelock_plus: ^1.2.10 #屏幕常亮
  battery_plus: ^6.2.1
  stop_watch_timer: ^3.2.1
  # storage
  file_picker: ^8.1.7
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.5
  flutter_cache_manager: ^3.3.1
  # utils
  get: 5.0.0-release-candidate-9.2.1
  intl: ^0.19.0
  timezone: ^0.10.0
  date_format: ^2.0.7
  path: ^1.8.3
  file: ^7.0.0
  path_provider: ^2.1.5
  logger: ^2.0.2+1
  crypto: ^3.0.3
  brotli: ^0.6.0
  flutter_restart: 
    git: https://ghfast.top/https://github.com/liuchuancong/flutterRestartPluginWip
  move_to_desktop: ^0.0.2
  dlna_dart: ^0.0.8
#  dart_tars_protocol:
#    git: https://ghfast.top/https://github.com/xiaoyaocz/dart_tars_protocol
  tars_dart:
    git:
      url: https://ghfast.top/https://github.com/xiaoyaocz/dart_simple_live
      path: ./simple_live_core/packages/tars_dart
  html_unescape: ^2.0.0
  flutter_inappwebview: ^6.1.5
  connectivity_plus: ^6.1.1
  qr_flutter: ^4.1.0 
  # 给web端通信
#  dia: ^0.1.5
  remixicon: ^1.3.0
#  dia_static: ^0.1.2
#  dia_body: ^0.1.3
#  dia_router: ^0.1.7
#  dia_cors: ^0.1.2
  mobile_scanner: ^6.0.2 #二维码扫描
  async_locks: ^4.0.2 #同步锁
  extended_image: ^9.1.0  #图片缓存
  uuid: ^4.4.2   # 用于生成 UUID
  auto_orientation: ^2.3.1 #屏幕方向
  device_info_plus: ^11.2.0 #设备信息
  canvas_danmaku: ^0.2.6    #弹幕
#  floating: ^5.0.1 #PIP画中画
  # PIP画中画
  fl_pip:
    git:
      url: https://ghfast.top/https://github.com/orz12/fl_pip.git
      ref: main

  catcher_2: ^2.1.0 #异常日志捕获
  loading_indicator: ^3.1.1 #加载中样式
 #  MPV 播放器
  media_kit:
    git:
      url: https://ghfast.top/https://github.com/Predidit/media-kit.git
      ref: main
      path: ./media_kit
  media_kit_video:
    git:
      url: https://ghfast.top/https://github.com/Predidit/media-kit.git
      ref: main
      path: ./media_kit_video
  media_kit_libs_video:
    git:
      url: https://ghfast.top/https://github.com/Predidit/media-kit.git
      ref: main
      path: ./libs/universal/media_kit_libs_video

dependency_overrides:
  media_kit:
    git:
      url: https://ghfast.top/https://github.com/Predidit/media-kit.git
      ref: main
      path: ./media_kit
  media_kit_video:
    git:
      url: https://ghfast.top/https://github.com/Predidit/media-kit.git
      ref: main
      path: ./media_kit_video
  media_kit_libs_video:
    git:
      url: https://ghfast.top/https://github.com/Predidit/media-kit.git
      ref: main
      path: ./libs/universal/media_kit_libs_video
  media_kit_libs_linux:
    git:
      url: https://ghfast.top/https://github.com/Predidit/media-kit.git
      ref: main
      path: ./libs/linux/media_kit_libs_linux
  media_kit_libs_ios_video:
    git:
      url: https://ghfast.top/https://github.com/Predidit/media-kit.git
      ref: main
      path: ./libs/ios/media_kit_libs_ios_video
  media_kit_libs_android_video:
    git:
      url: https://ghfast.top/https://github.com/Predidit/media-kit.git
      ref: main
      path: ./libs/android/media_kit_libs_android_video
  media_kit_libs_windows_video:
    git:
      url: https://ghfast.top/https://github.com/Predidit/media-kit.git
      ref: main
      path: ./libs/windows/media_kit_libs_windows_video
  media_kit_libs_macos_video:
    git:
      url: https://ghfast.top/https://github.com/Predidit/media-kit.git
      ref: main
      path: ./libs/macos/media_kit_libs_macos_video


dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: any
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
  protoc_builder: ^0.4.1
  flutter_launcher_icons: ^0.14.2
  msix: ^3.16.7

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# flutter pub run flutter_launcher_icons
flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: assets/icons/icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icons/icon_foreground.png
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: assets/icons/icon.png
    icon_size: 48 # min:48, max:256, default: 48

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/icons/
    - assets/keystore/supabase.json
    # - assets/pure_live_web/
    - assets/js/webmssdk.js
    - assets/js/
    # - assets/pure_live_web/assets/
    # - assets/pure_live_web/assets/assets/icons/
    # - assets/pure_live_web/assets/assets/images/
    # - assets/pure_live_web/assets/fonts/
    # - assets/pure_live_web/assets/packages/flex_color_picker/assets/
    # - assets/pure_live_web/assets/packages/flutter_js/assets/js/
    # - assets/pure_live_web/assets/packages/font_awesome_flutter/lib/fonts/
    # - assets/pure_live_web/assets/shaders/
    # - assets/pure_live_web/canvaskit/
    # - assets/pure_live_web/canvaskit/chromium/
    # - assets/pure_live_web/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icons/CustomIcons.ttf
    - family: PingFang
      fonts:
        - asset: assets/PingFangSC.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# flutter localization settings

flutter_intl:
  enabled: true
  arb_dir: lib/common/l10n
  output_dir: lib/common/l10n/generated

# windows msix package
# msix_config:
#   display_name: 纯粹直播
#   # publisher_display_name: puretech.com
#   # identity_name: com.puretech.purelive
#   msix_version: 1.0.0.65
#   logo_path: assets/icons/icon.png
#   # capabilities: internetClient
#   certificate_path: assets/keystore/CERTIFICATE.pfx
#   certificate_password: xxxx
#   # publisher: O=puretech.com, C=CN